# rust-toolchain.toml - Toolchain overrides file
# This file declares the Rust toolchain used by the project.
# Documentation: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
channel = "1.87.0"
components = ["rust-analyzer"]
