# This is a default home.nix generated by the follwing hone-manager command
#
# home-manager init ./

{ inputs, config, lib, pkgs, ... }:

{
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = lib.mkDefault "yilisharcs";
  home.homeDirectory = lib.mkDefault "/home/${config.home.username}";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "24.11"; # Please read the comment before changing.

  dconf.settings = with lib.hm.gvariant; {
    "org/gnome/GWeather4" = {
      temperature-unit = "centigrade";
    };
    "org/gnome/desktop/a11y" = {
      always-show-universal-access-status = true;
    };
    "org/gnome/desktop/a11y/interface" = {
      high-contrast = true;
      show-status-shapes = true;
    };
    "org/gnome/desktop/datetime" = {
      automatic-timezone = true;
    };
    "org/gnome/desktop/interface" = {
      accent-color = "green";
      color-scheme = "prefer-dark";
      cursor-size = 32;
      cursor-theme = "Bibata-Modern-Ice";
    };
    "org/gnome/desktop/input-sources" = {
      sources = [ (mkTuple [ "xkb" "br" ]) ];
    };
    "org/gnome/desktop/peripherals/keyboard" = {
      delay = lib.hm.gvariant.mkUint32 375;
      repeat = true;
      repeat-interval = lib.hm.gvariant.mkUint32 18;
    };
    "org/gnome/desktop/peripherals/keyboard" = {
      edge-scrolling-enabled = true;
      natural-scroll = false;
      two-finger-scrolling-enabled = false;
    };
    "org/gnome/desktop/sound" = {
      allow-volume-above-100-percent = true;
    };
    "org/gnome/desktop/wm/preferences" = {
      move-to-workspace-left = [ "<Shift><Super>minus" ];
      move-to-workspace-right = [ "<Shift><Super>equal" ];
      switch-to-workspace-left = [ "<Super>minus" ];
      switch-to-workspace-right = [ "<Super>equal" ];
    };
    "org/gnome/desktop/wm/preferences" = {
      button-layout = "appmenu:minimize,close";
      focus-mode = "sloppy";
    };
    "org/gnome/evince/default" = {
      inverted-colors = true;
      show-sidebar = false;
      sizing-mode = "fit-width";
    };
    "org/gnome/evolution/calendar" = {
      use-24hour-format = true;
    };
    "org/gnome/evolution/mail" = {
      composer-magic-smileys = true;
      # composer-mode = "html";
      composer-unicode-smileys = true;
      # hpaned-size = 1571673;
      image-loading-policy = "always";
      layout = 1;
      # paned-size = 1621669;
      message-list-sort-on-header-click = "always";
      show-animated-images = true;
      show-to-do-bar = false;
    };
    "org/gnome/evolution/plugin/external-editor" = {
      command = "neovide -- -c 'set spell'";
      launch-on-key-press = true;
    };
    "org/gnome/evolution/shell" = {
      icon-only-buttons-in-header-bar = true;
      statusbar-visible = false;
      webkit-minimum-font-size = 16;
    };
    "org/gnome/nautilus/preferences" = {
      click-policy = "single";
    };
    "org/gnome/settings-daemon/plugins/color" = {
      night-light-enabled = false; # TODO: set to true later
      night-light-schedule-automatic = false;
    };
    "org/gnome/settings-daemon/plugins/power" = {
      sleep-inactive-ac-type = "nothing";
    };
    "org/gnome/shell" = {
      favorite-apps = [
        "neovide.desktop"
        "org.gnome.Evolution.desktop"
        "brave-browser.desktop"
        "org.inkscape.Inkscape.desktop"
        "gimp.desktop"
        "org.gnome.Calendar.desktop"
        "org.gnome.Music.desktop"
        "org.gnome.Nautilus.desktop"
      ];
      last-selected-power-profile = "performance";
    };
    "org/gnome/shell/extensions/clipboard-indicator" = {
      clear-on-boot = false;
      disable-down-arrow = true;
      display-mode = 2;
      keep-selected-on-clear = true;
      move-item-first = true;
      notify-on-copy = false;
      notify-on-cycle = false;
      private-mode-binding = [ "<Control>F8" ];
      topbar-preview-size = 11;
    };
    "org/gnome/shell/extensions/dash-to-dock" = {
      background-opacity = 0.80000000000000004;
      dash-max-icon-size = 48;
      dock-position = "BOTTOM";
      height-fraction = 0.90000000000000002;
      intellihide-mode = "ALL_WINDOWS";
      multi-monitor = true;
      preferred-monitor = -2;
      preferred-monitor-by-connector = "LVDS-1";
    };
    "org/gnome/shell/extensions/vitals" = {
      hide-zeros = false;
      hot-sensors = [
        "_memory_usage_"
        "_system_load_1m_"
        "__network-rx_max__"
        "_storage_free_"
      ];
      icon-style = 0;
      menu-centered = true;
      position-in-panel = 0;
      show-battery = false;
      show-fan = false;
      use-higher-precision = false;
    };
    "org/gnome/shell/weather" = {
      automatic-location = true;
    };
    "org/gtk/gtk4/settings/file-chooser" = {
      show-hidden = true;
    };
    "org/gtk/settings/file-chooser" = {
      show-hidden = true;
      sort-directories-first = true;
    };
  };

  editorconfig = {
    enable = true;
    settings = {
      "*" = {
        charset = "utf-8";
        end_of_line = "lf";
        insert_final_newline = true;
        trim_trailing_whitespace = true;
      };
    };
  };

  systemd.user = {
    enable = true;
    services = {
      "ra-mux" = {
        Unit = {
          Description = "Rust-analyzer Multiplex Server";
        };
        Install = {
          WantedBy = [ "default.target" ];
        };
        Service = {
          Type = "simple";
          ExecStart = "${pkgs.ra-multiplex}/bin/ra-multiplex server";
          Restart = "on-failure";
        };
      };
    };
  };

  services = {
    # gnome = {
    #   gnome-keyring = {
    #     enable = true;
    #   };
    # };

    gpg-agent = {
      enable = true;
      enableSshSupport = true;
    };
  };

  programs = {

# I might be able to configure brave with chromium

    # background code checker
    bacon = {
      enable = true;
      settings = {
        summary = true;
        wrap = false;
        reverse = false;
        help_line = false;
        on_change_strategy = "kill_then_restart";
        exports.locations = {
          auto = false;
          exporter = "locations";
          path = ".bacon-locations";
          line_format = "{kind} {path}:{line}:{column} {message}";
        };
        sound.enabled = false;
      };
    };

    bash = {
      enable = true;
      # enableCompletion = true; # test with carapace first
      bashrcExtra = ''
        PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
        PROMPT_COMMAND='history -a'
        HISTTIMEFORMAT="%F %T "

        bind -x '"\C-g":"tmux-sessionizer"'
        bind    '"\C-o": edit-and-execute-command'
      '';
      historyControl = [ "ignoreboth" ];
      historyIgnore = [
        "vi"
        "vim"
        "nvim"
        ":q"
        "l[fs]"
        "pwd"
        "[bf]g"
        "tmuxa"
      ];
      shellAliases = {
        cp = "cp -iv";
        rm = "rm -I";
        ls = "ls --color=auto";
      };
      shellOptions = [
        "checkwinsize"
        "histappend"
      ];
    };

    # better cat
    bat = {
      enable = true;
      config = {
        pager = "less -FR";
        theme = "ansi";
      };
    };

    btop = {
      enable = true;
      settings = {
        color_theme = "adapta";
        theme_background = true;
        truecolor = true;
        force_tty = false;
        presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty";
        vim_keys = true;
        rounded_corners = true;
        graph_symbol = "braille";
        shown_boxes = "cpu proc net mem";
        update_ms = 1000;
        proc_sorting = "memory";
        proc_reversed = false;
        proc_tree = false;
        proc_colors = true;
        proc_gradient = false;
        proc_per_core = true;
        proc_mem_bytes = true;
        proc_cpu_graphs = true;
        proc_info_smaps = false;
        proc_left = false;
        proc_filter_kernel = true;
        proc_aggregate = false;
        cpu_graph_upper = "Auto";
        cpu_graph_lower = "total";
        show_gpu_info = "Auto";
        cpu_invert_lower = true;
        cpu_single_graph = true;
        cpu_bottom = false;
        show_uptime = true;
        check_temp = true;
        cpu_sensor = "Auto";
        show_coretemp = true;
        temp_scale = "celsius";
        base_10_sizes = false;
        show_cpu_freq = true;
        clock_format = "%X";
        background_update = true;
        mem_graphs = false;
        mem_below_net = false;
        zfs_arc_cached = true;
        show_swap = true;
        swap_disk = true;
        show_disks = true;
        only_physical = true;
        use_fstab = true;
        zfs_hide_datasets = false;
        disk_free_priv = false;
        show_io_stat = true;
        io_mode = false;
        io_graph_combined = true;
        net_download = 100;
        net_upload = 100;
        net_auto = true;
        net_sync = true;
        show_battery = true;
        selected_battery = "Auto";
        log_level = "WARNING";
        nvml_measure_pcie_speeds = true;
        gpu_mirror_graph = true;
      };
    };

    # multishell completion engine
    carapace = {
      enable = true;
    };

    # automatic invocation of shell.nix with .envrc
    direnv = {
      enable = true;
      nix-direnv.enable = true;
      # config = { };
    };

    # github cli tool
    gh = {
      enable = true;
      settings = {
        git_protocol = "ssh";
      };
    };

    # distributed version control system
    git = {
      enable = true;
      userName = "yilisharcs";
      userEmail = "yilisharcs@gmail.com";
      aliases = {
        graph = "log --decorate --oneline --graph";
        last = "log -1 HEAD";
        unstage = "reset HEAD --";
      };
      ignores = [
        ".env"
        "/blueprint"
      ];
    };

    gpg = {
      enable = true;
    };

    gnome-shell = {
      enable = true;
      extensions = with pkgs; [
        { package = gnomeExtensions.dash-to-dock; }
        { package = gnomeExtensions.clipboard-indicator; }
        { package = gnomeExtensions.vitals; }
      ];
    };

    # git-compatible version control system
    jujutsu = {
      enable = true;
      settings = {
        user = {
          name = "yilisharcs";
          email = "yilisharcs@gmail.com";
        };
        ui = {
          default-command = [ "log" "--reversed" ];
        };
        aliases = {
          init = [ "git" "init" ];
        };
      };
    };

    fastfetch = {
      enable = true;
      settings = {
        modules = [
          { type = "title"; }
          { type = "separator"; }
          { type = "os"; }
          { type = "host"; }
          { type = "kernel"; }
          { type = "uptime"; }
          { type = "packages"; }
          { type = "display"; }
          { type = "de"; }
          { type = "wm"; }
          { type = "cpu"; }
          { type = "gpu"; }
          { type = "memory"; }
          { type = "disk"; }
          { type = "break"; }
          { type = "colors"; }
        ];
      };
    };

    # better find
    fd = {
      enable = true;
      hidden = true;
    };

    # lf = {
    #   enable = true;
    #   previewer = "${pkgs.ctpv}/bin/bash";
    # };

    neovim = {
      enable = true;
      package = inputs.neovim-nightly-overlay.packages.${pkgs.system}.default;
      extraPackages = with pkgs; [
        gcc
      ];
      # withNodeJs = true;
      # withPython3 = true;
      # withRuby = true;
    };

    # graphical neovim client
    neovide = {
      enable = true;
      settings = {
        font = {
          normal = [
            "JetBrainsMono Nerd Font"
            "Noto Color Emoji"
          ];
          size = 13;
        };
        maximized = true;
        no-multigrid = false;
        wsl = false;
      };
    };

    nushell = {
      enable = true;
      envFile.text = ''
        $env.SUDO_PROMPT = $'(ansi red_bold)[sudo](ansi reset) password for %u: '
      '';
      plugins = with pkgs.nushellPlugins; [
        gstat
        highlight #regex
        query
        # skim  ### NOTE: these seem to be outdated
        # units ### NOTE: mismatched versions
      ];
      configFile.text = ''
        $env.config.plugin_gc = {
          default: {
            enabled: true
            stop_after: 10sec
          }
          plugins: {
            gstat: { stop_after: 1min }
            inc: { stop_after: 0sec }
          }
        }
      '';
      settings = {
        show_banner = false;
        buffer_editor = "nvim";
        history = {
          file_format = "plaintext";
          max_size = 10000000;
          sync_on_enter = true;
          isolation = false;
        };
        keybindings = [
          {
            name = "job_to_foreground";
            modifier = "control";
            keycode = "char_z";
            mode = [ "emacs" "vi_insert" "vi_normal" ];
            event = {
              send = "executehostcommand";
              cmd = "job unfreeze";
            };
          }
          {
            name = "fuzzy_history";
            modifier = "control";
            keycode = "char_r";
            mode = [ "emacs" "vi_normal" "vi_insert" ];
            event = {
              send = "executehostcommand";
              cmd = ''commandline edit --replace (
                history
                | get command
                | reverse
                | uniq
                | str join (char -i 0)
                | ^sk
                --read0
                --layout reverse
                --query (commandline)
                --preview-window hidden
                | decode utf-8
                | str trim
              )'';
            };
          }
        ];
      };
      # shellAliases = { };
    };

    # better grep
    ripgrep-all.enable = true;
    ripgrep = {
      enable = true;
      arguments = [
        "--hidden"
        "--follow"
        "--glob=!.cache/*"
        "--glob=!.git/*"
        "--glob=!.npm/*"
        "--glob=!Trash/*"
        "--smart-case"
      ];
    };

    # fuzzy finder
    skim = {
      enable = true;
      # # FIXME: none of these options are working
      # defaultCommand = "fd --color=never --hidden --follow --type f --type l --exclude .git";
      # defaultOptions = [
      #   "--preview 'bat {} --color=always --wrap=never --style=plain --line-range=:500'"
      #   "--layout=reverse"
      #   "--multi"
      #   "--bind='ctrl-j:preview-page-down'"
      #   "--bind='ctrl-k:preview-page-up'"
      #   "--bind='ctrl-h:backward-char+delete-charEOF'"
      #   "--bind='F4:toggle-preview'"
      # ];
    };

    ssh = {
      enable = true;
      addKeysToAgent = "ask";
    };

    # multishell prompt engine
    starship = {
      enable = true;
      enableBashIntegration = false;
      settings = {
        add_newline = false;
        command_timeout = 300;
        character = {
          success_symbol = "[➜](bold green)";
          error_symbol = "[➜](bold red)";
        };
        git_status = {
          format = lib.concatStrings [
            "([\\["
            "$all_status"
            "$ahead_behind"
            "\\]]("
            "$style"
            ") )"
          ];
          deleted = "[✕](italic red)";
        };
        package.format = "(is [󰏗 $version]($style) )";
        time = {
          disabled = false;
          format = " [$time]($style)";
          style = "bold green";
          time_format = "%a %F %T";
          use_12hr = false;
        };
        fill.symbol = " ";
        format = lib.concatStrings [
          "$all"
          "$fill"
          "$time"
          "$line_break"
          "$jobs"
          "$battery"
          "$status"
          "$os"
          "$container"
          "$netns"
          "$shell"
          "$character"
        ];
      };
    };

    # terminal multiplexer
    tmux = {
      enable = true;
      focusEvents = true;
      mouse = true;
    };

    # YouTube downloader
    yt-dlp = {
      enable = true;
      settings = {
        extract-audio = true;
        no-mtime = true;
        no-playlist = true;
      };
      extraConfig = ''
        -o ~/YouTube/%(title)s.%(ext)s
        -f bv*[height<=?1080]+ba/best
      '';
    };

    # zettelkasten helper
    zk = {
      enable = true;
      settings = {
        notebook = {
          dir = "~/notebook";
        };
        note = {
          language = "en";
          default-title = "Untitled";
          filename = "{{id}}-{{slug title}}";
          extension = "md";
          template = "default.md";
          id-charset = "hex";
          id-length = 7;
          id-case = "lower";
        };
        extra = {
          author = "以利沙";
        };
        group.journal = {
          paths = ["journal/weekly" "journal/daily"];
          note.filename = "{{format-date now}}";
        };
        format.markdown = {
          hashtags = false;
          colon-tags = false;
          multiword-tags = true;
        };
        tool = {
          editor = "nvim";
          shell = "${pkgs.bash}/bin/bash";
          pager = "less -FRX";
          fzf-preview = "bat -p --color always {-1}";
        };
        lsp.diagnostics = {
          wiki-title = "hint";
          dead-link = "error";
        };
        filter = {
          recents = "--sort created- --created-after 'last two weeks'";
        };
        alias = {
          ls = "zk list $@";
          list = "zk list --quiet $@";
          editlast = "zk edit --limit 1 --sort modified- $@";
          recent = "zk edit --sort created- --created-after 'last two weeks' --interactive";
          path = "zk list --quiet --format {{path}} --delimiter , $@";
          lucky = "zk list --quiet --format full --sort random --limit 1";
          hist = "zk list --format path --delimiter0 --quiet $@ | xargs -t -0 git log --patch --";
        };
      };
    };

    # better cd
    zoxide = {
      enable = true;
    };
  };

  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "x-scheme-handler/mailto" = "userapp-Evolution-I70E62.desktop";
    };
    associations = {
      added = {
        "application/x-zerosize" = "neovide.desktop";
      };
    };
  };

  home.shell.enableBashIntegration = true;
  home.shell.enableNushellIntegration = true;

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = with pkgs; [
    # Adds the 'hello' command to your environment. It prints a friendly
    # "Hello, world!" when run.
    # pkgs.hello

    atool                          # compression and extraction tools
    chafa                          # terminal image visualizer
    ctpv                           # lf previewer
    dconf-editor
    evolution                      # mail client
    ffmpeg
    ffmpegthumbnailer
    file                           # isn't this a core-util?
    gimp                           # image editor
    gnome-tweaks
    # imagemagick
    inkscape                       # image editor
    man-pages                      # Linux man pages
    mesa                           # graphics lib
    obs-studio
    pandoc                         # markup converter
    # picard                         # music metadata editor
    porsmo                         # cli pomodoro app
    qbittorrent
    speedtest-rs
    stow                           # symlink manager
    trash-cli
    tree                           # dir viewer

    # LSP
    lua-language-server
    nil
    vim-language-server

    # dev libs and tools
    cargo-audit
    cargo-auditable
    cargo-binstall
    cargo-generate
    cargo-modules
    cargo-nextest
    cargo-sweep
    cargo-update
    dioxus-cli
    # fnm                            # fast node version manager
    # go
    jq                             # cli json processor
    mold                           # better linker
    # pipx                           # python package manager
    # python314
    ra-multiplex                   # rust-analyzer multiplex server
    rustup                         # rust toolchain manager
    sccache                        # build cache tool
    sqlite
    tokei                          # loc counter

    # # It is sometimes useful to fine-tune packages, for example, by applying
    # # overrides. You can do that directly here, just don't forget the
    # # parentheses. Maybe you want to install Nerd Fonts with a limited number of
    # # fonts?
    # (pkgs.nerdfonts.override { fonts = [ "FantasqueSansMono" ]; })

    # # You can also create simple shell scripts directly inside your
    # # configuration. For example, this adds a command 'my-hello' to your
    # # environment:
    # (pkgs.writeShellScriptBin "my-hello" ''
    #   echo "Hello, ${config.home.username}!"
    # '')
  ];

  # Home Manager is pretty good at managing dotfiles. The primary way to manage
  # plain files is through 'home.file'.
  home.file = {
    # # Building this configuration will create a copy of 'dotfiles/screenrc' in
    # # the Nix store. Activating the configuration will then make '~/.screenrc' a
    # # symlink to the Nix store copy.
    # ".screenrc".source = dotfiles/screenrc;

    # # You can also set the file content immediately.
    # ".gradle/gradle.properties".text = ''
    #   org.gradle.console=verbose
    #   org.gradle.daemon.idletimeout=3600000
    # '';
  };

  # Home Manager can also manage your environment variables through
  # 'home.sessionVariables'. If you don't want to manage your shell through Home
  # Manager then you have to manually source 'hm-session-vars.sh' located at
  # either
  #
  #  ~/.nix-profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  /etc/profiles/per-user/m3tam3re/etc/profile.d/hm-session-vars.sh

  home.sessionVariables = {
    SUDO_EDITOR = "nvim";
    VISUAL = "nvim";
    EDITOR = "nvim";
    SQLITE_HISTORY = "${config.home.homeDirectory}/.local/state/sqlite3/sqlite_history";
    STARSHIP_LOG = "error";
    # TODO: remove this once the problem is fixed
    SKIM_DEFAULT_COMMAND = "fd --color=never --hidden --follow --type f --type l --exclude .git";
    SKIM_DEFAULT_OPTIONS = lib.concatStrings [
      "--preview 'bat {} --color=always --wrap=never --style=plain --line-range=:500' "
      "--layout=reverse "
      "--multi "
      "--bind='ctrl-j:preview-page-down' "
      "--bind='ctrl-k:preview-page-up' "
      "--bind='ctrl-h:backward-char+delete-charEOF' "
      "--bind='F4:toggle-preview'"
    ];

  };

  home.shellAliases = {
    # muscle memory
    vi = "nvim";
    vim = "nvim";
    ":q" = "exit";

    # convenience
    grep = "grep --color=auto";
    fetch = "fastfetch";
    nsp = "nix search nixpkgs";
    pomo = "porsmo";
    speedtest = "speedtest-rs";
    # wiki = "wiki-tui";

    # # nushell scripts
    # gitcon = "gitcon.nu";
    # gitlist = "gstat.nu";
    # tokeicon = "tokeicon.nu";
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
}
